feat: Add probe mode in debugger
nervosnetwork/ckb-standalone-debugger pull request #62
Opened 2023-03-01 02:18 UTC by xxuejie

This change introduces a new probe mode in ckb-debugger, which provides uprobes exposing ckb-vm's full register state. We have to use 3 uprobes, since uprobe has limits on the arguments supported.

2023-03-01 02:29 UTC, XuJiandong requested changes

2023-03-01 02:29 UTC, XuJiandong commented on ckb-debugger/src/main.rs
> +                        let ra = machine.registers()[registers::RA];
It's better to use one probe to expose a memory pointer to registers at startup:
https://github.com/nervosnetwork/ckb-vm/pull/272/files#diff-7de6cee2dbf7962fc5e95c3cedd3d5b9f27b720544c9941663f1b329d704bba6R79-R81

And let bpftrace locate register if needed.

2023-03-01 02:36 UTC, xxuejie commented on ckb-debugger/src/main.rs
> +                        let ra = machine.registers()[registers::RA];
Done, thanks for the suggestion.

2023-03-01 02:38 UTC, XuJiandong approved these changes

2023-03-02 05:38 UTC, xxuejie commented
This is now updated to expose memory in probes as well. Since it's hard to look into actual memory content when using SparseMemory, we also change the code to use FlatMemory when `probes` feature is enabled.

2023-03-10 06:03 UTC, xxuejie commented
Waiting for https://github.com/nervosnetwork/ckb/pull/3859 to land in a proper CKB release, then we will rebase this PR and (hopefully) merge it to tip.

2023-04-13 01:52 UTC, contrun commented on ckb-debugger/src/main.rs
> +                        probe!(
In https://github.com/nervosnetwork/ckb-standalone-debugger/pull/71, I tried to add two additional user-friendly probe for syscalls and functions. I also added helper scripts two probe function calls and returns in https://github.com/contrun/ckb-vm-bpf-toolkit/tree/uretprobe/. In order for typical ckb developers to use these probes. I think we need to document them. Once we document them, we need to keep them more or less stable. I think `regs` and `memory` are two quite useful common arguments for all these probes. Can we make them as the first and second arguments for all probes? We need also change the helper scripts in https://github.com/xxuejie/ckb-vm-bpf-toolkit.

2023-04-19 05:41 UTC, xxuejie commented on ckb-debugger/src/main.rs
> +                        probe!(
I wasn't sure about the 2 new probes for syscalls and functions. To me, we can reuse the generic probe, and does syscall / function call detection within BPF scripts. Adding new probes here might be an endless path: today we decided syscalls are important, what if one day we noticed that jumps are important as well? Or instructions touching SP is important? I do suggest a different path where we build more features within BPF code, not adding more probes.

I don't have any preferences on argument orders, tho, we can discuss them here, once there is a finalized order, I can make the change.

2023-04-19 05:58 UTC, XuJiandong approved these changes

2023-04-20 00:45 UTC, merged