Add new DSL statement: def_type & ref_type
nervosnetwork/ckb-standalone-debugger pull request #69
Opened 2023-04-09 08:30 UTC by mohanson

Add two rules for preprocessing of tx_file:

- replace `{{ def_type ANY_NAME }}` to `{
            "code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944",
            "hash_type": "type",
            "args": "hex(ANY_NAME)"
          }`
- replace `{{ ref_type ANY_NAME }}` to hex data calculated by `script_hash(type_id_ANY_NAME)`

2023-04-09 08:48 UTC, XuJiandong requested changes

2023-04-09 08:48 UTC, XuJiandong commented on ckb-debugger/src/main.rs
> +                return format!("0x{}", hex::encode(&blake2b_256(read_file(cap2))));
Remove "0x". We need following combination: <type>, <hash(data)>

2023-04-09 08:48 UTC, XuJiandong commented on ckb-debugger/src/main.rs
> +                return format!("0x{}", hex::encode(read_file(cap2)));
It's not necessary to remove this "0x" here. For the sake of consistency, it is better to remove "0x".

2023-04-09 08:48 UTC, XuJiandong commented on ckb-debugger/src/main.rs
> +            mock_type_id_dict.insert(type_id_name.to_string(), type_id_script_hash);
Report error if type_id_name is already existing.

2023-04-09 13:55 UTC, mohanson commented on ckb-debugger/src/main.rs
> +            mock_type_id_dict.insert(type_id_name.to_string(), type_id_script_hash);
Fixed

2023-04-10 00:08 UTC, XuJiandong approved these changes

2023-04-10 00:08 UTC, merged